# https://taskfile.dev

version: '3'

dotenv: ["internal/config/.env"]

vars:
  GREETING: Hello, World!

tasks:
  default:
    deps: [setup_db, build]
    cmds:
      - echo "Welcome to the Guddy Program!"
      - echo "Project setup Completed successfully"
    silent: true

  setup_db:
    cmds:
      - echo "Setting up the database..."
      - task: migrate
      - task: import_data
      - echo "Database setup completed successfully."
    silent: true

  build:
    cmds:
      - echo "Generating Swagger docs"
      - task: build-docs
      - echo "Compiling SQL queries with sqlc..."
      - sqlc generate
      - echo "SQL queries compiled successfully."
      - echo "Compiling the Guddy Program"
      - go mod tidy
      - go mod verify
      - go build -o build github.com/Farzan-Kh/guddy-cn
      - echo "Guddy Compiled successfully."
    silent: true
  
  build-docs:
    cmds:
      - swag init
    silent: true

  migrate:
    cmds:
      - task: migrate_up
    silent: true

  migrate_up:
    cmds:
      - echo "Running migrations..."
      - migrate -path internal/db/migrate -database "$DATABASE_URL" up
      - echo "Migrations completed successfully."
    silent: true

  migrate_down:
    cmds:
      - echo "Running down migrations..."
      - migrate -path internal/db/migrate -database "$DATABASE_URL" down
      - echo "Migrations completed successfully."
    silent: true

  import_data:
    cmds:
      - echo "Importing data..."
      - python3 data/import_script.py
      - echo "Data import completed successfully."
    silent: true
