apiVersion: apps/v1
kind: Deployment
metadata:
  name: authn-service
  namespace: guddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authn-service
  template:
    metadata:
      labels:
        app: authn-service
    spec:
      containers:
        - name: authn-service
          image: ghcr.io/farzan-kh/guddy-cn/authn:06d467b88dd978960455717b15974936cbfab4b3
          envFrom:
            - configMapRef:
                name: guddy-config
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: authn-service
  namespace: guddy
spec:
  type: ClusterIP
  selector:
    app: authn-service
  ports:
    - port: 8084
      targetPort: 8084
