apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises-service
  namespace: guddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises-service
  template:
    metadata:
      labels:
        app: exercises-service
    spec:
      containers:
        - name: exercises-service
          image: ghcr.io/farzan-kh/guddy-cn/exercises:${GITHUB_SHA}
          envFrom:
            - configMapRef:
                name: guddy-config
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: exercises-service
  namespace: guddy
spec:
  type: ClusterIP
  selector:
    app: exercises-service
  ports:
    - port: 8081
      targetPort: 8081
