apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: guddy
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP

# Optional: if you also run a headless service for stateful sets or discovery,
# add another Service with `clusterIP: None` and a different name (e.g. redis-headless).

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: guddy
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2

      # If you want persistence, add a PVC and volumeMount here (not included by default).
