name: Build Gateway

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'services/gateway/**'
      - '.github/workflows/build-gateway.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'services/gateway/**'
      - '.github/workflows/build-gateway.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.24.6'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies for gateway module
      working-directory: ./services/gateway
      run: go mod download

    - name: Build gateway module
      working-directory: ./services/gateway
      run: go build -o build/ ./...