name: Build Exercises

on:
  push:
    branches:
      - main
    paths:
      - 'services/exercises/**'
      - '.github/workflows/build-exercises.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'services/exercises/**'
      - '.github/workflows/build-exercises.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.24.6'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install sqlc
      run: |
      curl -sSL https://github.com/sqlc-dev/sqlc/releases/latest/download/sqlc-linux-amd64.tar.gz | tar -xz -C /usr/local/bin sqlc

    - name: Generate SQL code with sqlc
      working-directory: ./services/exercises
      run: sqlc generate

    - name: Install dependencies for exercises module
      working-directory: ./services/exercises
      run: go mod download

    - name: Build exercises module
      working-directory: ./services/exercises
      run: go build -o build/ ./...