name: Build and Push Gateway Docker Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Gateway"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_NAME/gateway:latest ./services/gateway
          docker push ghcr.io/$REPO_NAME/gateway:latest

      - name: Make Docker image public
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/$REPO_NAME/gateway"
          gh api \
            --method PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "/users/${{ github.actor }}/packages/container/${IMAGE_NAME#ghcr.io/}/versions/latest" \
            -f visibility=public
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}